;;; cooked-tests-oracle.el --- The Lisp half of the renderer against a reference -*- lexical-binding: t; -*-

;;; Commentary:

;; `tests/delta_replay.rs' checks the drain against the grid it came from, but it
;; replays the deltas into a Rust model of the buffer.  Everything Lisp does with a
;; drain -- `cooked--apply-shift', a coalesced block, an edit by character offset,
;; a glyph run cut at the cursor, `cooked--pad-to-cursor', `cooked--protect' -- is
;; outside it, and a difference between that model and Lisp leaves a row wrong
;; until the child happens to write different cells to it.
;;
;; So this runs the real thing twice.  One generated byte script is fed, a chunk at
;; a time, into two cooked buffers, and both are drained and applied after every
;; chunk.  The subject is drained as a user's buffer is.  The reference has every
;; row damaged before each drain (`cooked--redraw'), which also drops the core's
;; copy of what Emacs holds and the drain's shift log, so it receives no shifts, no
;; edits and no left-out rows: every live row arrives whole.  After each drain the
;; two buffers must hold the same text under the same text properties.
;;
;; The cases are generated here in Lisp, from a seeded Park-Miller generator,
;; rather than read from a corpus a Rust generator wrote.  The reason is
;; shrinking.  A failing case is re-run in the same Emacs as often as the shrinker
;; likes, dropping chunks, merging them and dropping tokens, and what is printed is
;; the seed and the smallest script that still fails, as a form a regression test
;; can quote verbatim.  A corpus from Rust would shrink against the Rust model
;; instead, which is the one thing this exists not to trust, or it would need a
;; round trip per shrinking step.
;;
;; `cooked-tests--oracle-compare' is the harness, and takes the two treatments as
;; functions, so a later comparison ("promoted against resent", a narrower
;; `cooked--protect') is a new pair of functions and possibly new motifs rather
;; than a new harness.
;;
;; Not covered: the width guard, which needs a window with real font metrics, and
;; so rows it trimmed; pending input, which needs a line editor reading; and the
;; URLs and file names redisplay finds, which are scanned when a row is shown
;; rather than when it is drawn.  An `OSC 8' span is drawn, and is compared.

;;; Code:

(require 'cooked-tests-helpers)

;;;; A seeded generator

(defun cooked-tests--oracle-rng (seed)
  "A generator state for SEED, any integer.

Park-Miller's minimal standard, whose state has to be in 1 .. 2^31-2, so SEED is
folded into that range.  Its own arithmetic rather than `random', so that a seed
printed by one Emacs names the same case in another: `random' seeded with a
string is deterministic only within one build."
  (list (1+ (mod seed 2147483646))))

(defun cooked-tests--oracle-below (rng n)
  "The next number from RNG, from 0 below N."
  (setcar rng (% (* (car rng) 48271) 2147483647))
  (% (car rng) n))

(defun cooked-tests--oracle-pick (rng choices)
  "One of the list CHOICES, chosen by RNG."
  (nth (cooked-tests--oracle-below rng (length choices)) choices))

(defconst cooked-tests--oracle-lines
  '("abc" "$ ls" "日本語" "┌──┐" "│ x │" "├─┤" "e\u0301e\u0301" " 42%")
  "Whole lines a repaint writes, few enough that one comes round again.

A program repainting with the same text is what makes the core leave a row
out, and a line written back with a single cell changed is what makes it send
an edit, so both need a line to have been seen before.")

(defconst cooked-tests--oracle-motifs
  '((text . 8) (line . 4) (wrap . 2) (newline . 5) (cup . 5) (move . 3)
    (erase . 4) (insert-delete . 3) (scroll . 3) (region . 2) (sgr . 3)
    (alt . 1) (link . 2) (rewrite . 4) (cell . 5) (save . 1) (autowrap . 1)
    (clear . 1))
  "The kinds of token a script is made of, each with its weight.

`rewrite' and `cell' are the two the task asks for by name: erasing a row and
writing a line back over it, and addressing one cell and writing one character
there, which is a spinner and a TUI's cursor-addressed field.")

(defun cooked-tests--oracle-motif (rng rows cols)
  "One token of a script for a ROWS by COLS screen, chosen by RNG.

Nothing here asks the terminal a question.  A reply goes back to the child
through the pty, whose echo sends it round again as output that a reader
thread feeds at a moment of its own choosing, which is exactly the
nondeterminism `cooked--feed' exists to keep out."
  (let* ((total (apply #'+ (mapcar #'cdr cooked-tests--oracle-motifs)))
         (roll (cooked-tests--oracle-below rng total))
         (kind (cl-loop for (kind . weight) in cooked-tests--oracle-motifs
                        if (< roll weight) return kind
                        do (setq roll (- roll weight))))
         (n (lambda (limit) (1+ (cooked-tests--oracle-below rng limit)))))
    (pcase kind
      ('text (cooked-tests--oracle-pick
              rng '("a" "xy" "hello" "日" "本x" "e\u0301" "─" "│ │" "┌─" "┐"
                    " " "https://e.x/a")))
      ('line (cooked-tests--oracle-pick rng cooked-tests--oracle-lines))
      ;; Past the right margin, so the line wraps, or with DECAWM off overwrites the
      ;; last column.
      ('wrap (make-string (+ cols (funcall n 3)) (cooked-tests--oracle-pick rng '(?= ?w ?─))))
      ('newline (cooked-tests--oracle-pick rng '("\r\n" "\r\n" "\n" "\r" "\b" "\t")))
      ('cup (format "\e[%d;%dH" (funcall n (1+ rows)) (funcall n (1+ cols))))
      ('move (format "\e[%d%c" (funcall n 3) (cooked-tests--oracle-pick rng '(?A ?B ?C ?D ?G))))
      ('erase (cooked-tests--oracle-pick
               rng (list "\e[K" "\e[1K" "\e[2K" "\e[J" "\e[1J" "\e[2J"
                         (format "\e[%dX" (funcall n 3))
                         (format "\e[%dP" (funcall n 3))
                         (format "\e[%d@" (funcall n 3)))))
      ('insert-delete (format "\e[%d%c" (funcall n rows) (cooked-tests--oracle-pick rng '(?L ?M))))
      ('scroll (cooked-tests--oracle-pick
                rng (list (format "\e[%dS" (funcall n 2)) (format "\e[%dT" (funcall n 2))
                          "\eM" "\eD" "\eE")))
      ('region (if (zerop (cooked-tests--oracle-below rng 3))
                   "\e[r"
                 (let ((top (funcall n rows)))
                   (format "\e[%d;%dr" top (+ top (cooked-tests--oracle-below rng rows))))))
      ('sgr (cooked-tests--oracle-pick
             rng '("\e[31m" "\e[1;42m" "\e[0m" "\e[7m" "\e[4m" "\e[38;5;208m")))
      ('alt (cooked-tests--oracle-pick rng '("\e[?1049h" "\e[?1049l" "\e[?47h" "\e[?47l")))
      ('link (if (zerop (cooked-tests--oracle-below rng 2))
                 "\e]8;;\e\\"
               (format "\e]8;;https://e.x/%d\e\\" (cooked-tests--oracle-below rng 3))))
      ('rewrite (format "\e[%d;1H\e[2K%s" (funcall n rows)
                        (cooked-tests--oracle-pick rng cooked-tests--oracle-lines)))
      ('cell (format "\e[%d;%dH%s" (funcall n rows) (funcall n cols)
                     (cooked-tests--oracle-pick rng '("|" "/" "-" "─" "日" " " "x"))))
      ('save (cooked-tests--oracle-pick rng '("\e7" "\e8")))
      ('autowrap (cooked-tests--oracle-pick rng '("\e[?7l" "\e[?7h")))
      ('clear (cooked-tests--oracle-pick rng '("\e[H\e[2J" "\e[3J" "\ec"))))))

(defun cooked-tests--oracle-generate (seed)
  "The case SEED names, a plist of :rows, :cols, :rejoin and :chunks.

:chunks is a list of chunks, each a list of tokens: what is fed between two
drains.  A cut falls only between tokens.  Cutting inside an escape sequence is
the parser's business, which the Rust suite covers; what reaches Lisp is the
grid as of a drain, and a cut between tokens already puts a drain between any
two things the child did."
  (let* ((rng (cooked-tests--oracle-rng seed))
         (rows (+ 2 (cooked-tests--oracle-below rng 5)))
         (cols (+ 4 (cooked-tests--oracle-below rng 9)))
         ;; One chance in N of a drain after each token, N from 1 to 8, so some
         ;; cases drain after every token and some rarely at all.
         (cut (1+ (cooked-tests--oracle-below rng 8)))
         (chunks nil)
         (chunk nil))
    (dotimes (_ (1+ (cooked-tests--oracle-below rng 40)))
      (push (cooked-tests--oracle-motif rng rows cols) chunk)
      (when (zerop (cooked-tests--oracle-below rng cut))
        (push (nreverse chunk) chunks)
        (setq chunk nil)))
    (when chunk (push (nreverse chunk) chunks))
    (setq chunks (nreverse chunks))
    (list :rows rows :cols cols
          ;; Never rejoined with the alternate screen in the script.  A wrapped
          ;; row that scrolled away before the switch leaves `cooked--screen-start'
          ;; mid-line while the drain's `:head' says 0, and one that scrolls away
          ;; in the drain that switches is given a newline while the primary's
          ;; carry still counts it, so `cooked--check-seam' signals either way; see
          ;; `cooked-render-oracle-the-alternate-screen-and-a-rejoined-seam'.
          :rejoin (and (/= 0 (cooked-tests--oracle-below rng 4))
                       (not (seq-some (lambda (token)
                                        (member token '("\e[?1049h" "\e[?1049l" "\e[?47h" "\e[?47l")))
                                      (apply #'append chunks))))
          :chunks chunks)))

;;;; Running a case

(defun cooked-tests--oracle-buffer (rows cols)
  "A cooked buffer with a ROWS by COLS session whose child writes nothing.

Everything the emulator sees arrives through `cooked--feed'.  The cell size is
set so box glyphs are drawn as images, which is what cuts a glyph run at the
cursor; see `cooked-tests--cell'."
  (let ((buffer (generate-new-buffer " *cooked-oracle*")))
    (with-current-buffer buffer
      (cooked-mode)
      (cooked--start '("sleep" "600"))
      (setq cooked--rows rows cooked--cols cols
            cooked--last-size (cons rows cols))
      (cooked--resize cooked--session rows cols)
      (cooked-tests--cell 10 20))
    buffer))

(defun cooked-tests--oracle-resend ()
  "Damage every row of this buffer's session, so the next drain sends them whole.

The reference treatment: see the Commentary."
  (cooked--redraw cooked--session))

;; Two things differ between the buffers by history alone, and neither is
;; rendering, so a snapshot leaves both out.
;;
;; Spaces `cooked--pad-to-cursor' added stay on a row after the cursor leaves it,
;; until something rewrites the row; an edit takes them away, and so does resending
;; the row, which is what the reference does on every drain.  A row's own trailing
;; blanks never reach the buffer, since the core trims them, so a space at the end of
;; a line with no face on it can only be padding.
;;
;; And whether the primary's last row is terminated.  `cooked--fit-screen' trims the
;; region from the start of the row past the last used one, which keeps the newline
;; ending the row above it, while a row made to exist by being written into is left
;; unterminated.  So a blank row resent below the content leaves a newline behind
;; that the same screen reached by drawing only its content does not have.

(defun cooked-tests--oracle-properties (plist)
  "PLIST as a sorted alist, without the properties that say nothing about rendering.

`fontified' is jit-lock's note of what redisplay has seen, and a nil value is
the same as no property at all.  A box glyph's `cooked-deco' record keeps only
its kind and pattern: the column and row after them say where the run was
drawn, nothing reads them back, and a row a shift moved keeps the row it was
drawn on where the same row resent says where it is now.

The stickiness in `cooked--read-only-props' means something only beside
`read-only' itself: `cooked--protect' lifts `read-only' from text the input
line moves over and leaves the stickiness, which on text that is not read-only
has nothing to make sticky, while the same text resent arrives with neither."
  (let ((rest plist)
        pairs)
    (while rest
      (unless (or (memq (car rest) '(fontified front-sticky rear-nonsticky))
                  (null (cadr rest)))
        (push (cons (car rest)
                    (pcase (cadr rest)
                      ((and `(,(or 'glyph 'shade) ,pattern . ,_) deco)
                       (list (car deco) pattern))
                      (value value)))
              pairs))
      (setq rest (cddr rest)))
    (when (assq 'read-only pairs)
      (setq pairs (append (list (cons 'front-sticky (plist-get plist 'front-sticky))
                                (cons 'rear-nonsticky (plist-get plist 'rear-nonsticky)))
                          pairs)))
    (sort pairs (lambda (a b) (string< (car a) (car b))))))

(defun cooked-tests--oracle-place (pos)
  "POS as (LINE . COLUMN), both counted from zero, or nil for nil.

Lines rather than positions, because the padding a snapshot leaves out moves
every position after it."
  (when pos
    (save-excursion
      (goto-char pos)
      (cons (1- (line-number-at-pos pos t)) (- pos (line-beginning-position))))))

(defun cooked-tests--oracle-snapshot ()
  "What the current buffer shows, as a plist that `equal' can compare.

:lines is the whole buffer, scrollback included, one entry per line, and each
entry is a list of (TEXT . PROPERTIES) runs, adjacent characters with equal
properties merged, since where Emacs happens to split an interval is not
something anyone sees.  :screen-start and :point are places as
`cooked-tests--oracle-place' gives them, and :alt is the screen shown.  See
above for the padding and the final newline, which are left out."
  (save-restriction
    (widen)
    (let* ((text (buffer-substring (point-min) (point-max)))
           (lines (split-string text "\n")))
      (when (and (cdr lines) (equal (car (last lines)) ""))
        (setq lines (butlast lines)))
      (list :lines
            (mapcar
             (lambda (line)
               (let ((end (length line)))
                 (while (and (> end 0) (eq (aref line (1- end)) ?\s)
                             (not (get-text-property (1- end) 'face line)))
                   (setq end (1- end)))
                 (let ((pos 0) runs)
                   (while (< pos end)
                     (let ((next (next-property-change pos line end))
                           (props (cooked-tests--oracle-properties
                                   (text-properties-at pos line))))
                       (if (and runs (equal (cdar runs) props))
                           (setcar (car runs) (concat (caar runs)
                                                      (substring-no-properties line pos next)))
                         (push (cons (substring-no-properties line pos next) props) runs))
                       (setq pos next)))
                   (nreverse runs))))
             lines)
            :screen-start (cooked-tests--oracle-place (cooked--screen-start-position))
            :point (cooked-tests--oracle-place (point))
            :alt cooked--alt))))

(defun cooked-tests--oracle-text (snapshot)
  "SNAPSHOT's text, lines joined, for a failure message."
  (mapconcat (lambda (line) (mapconcat #'car line "")) (plist-get snapshot :lines) "\n"))

(defun cooked-tests--oracle-difference (subject reference)
  "Where snapshot SUBJECT first differs from snapshot REFERENCE, or nil.

A plist naming the first line that differs, with both versions of it and the
whole text of each buffer, or the first other field that differs, so a failure
reads without a diff tool."
  (let ((have (plist-get subject :lines))
        (want (plist-get reference :lines))
        (line 0))
    (while (and (or have want) (equal (car have) (car want)))
      (setq have (cdr have) want (cdr want) line (1+ line)))
    (if (or have want)
        (list :line line :have (car have) :expected (car want)
              :text (cooked-tests--oracle-text subject)
              :expected-text (cooked-tests--oracle-text reference))
      (cl-loop for key in '(:screen-start :point :alt)
               unless (equal (plist-get subject key) (plist-get reference key))
               return (list key (plist-get subject key)
                            :expected (plist-get reference key))))))

(defun cooked-tests--oracle-drain (buffer rejoin treatment)
  "Run TREATMENT in BUFFER, then drain and apply its session under REJOIN."
  (with-current-buffer buffer
    (funcall treatment)
    (let ((cooked-rejoin-wrapped-lines rejoin))
      (cooked--drain-and-apply))))

(defun cooked-tests--oracle-compare (case &optional subject reference)
  "Run CASE into two buffers and return where they first differ, or nil.

CASE is a plist as `cooked-tests--oracle-generate' makes one.  SUBJECT and
REFERENCE are functions run in their buffer before each drain; SUBJECT defaults
to doing nothing, the ordinary drain, and REFERENCE to
`cooked-tests--oracle-resend'.  After every drain the two buffers are compared,
and the first difference is returned as a plist with :drain, the index of the
chunk just fed, and :difference, from `cooked-tests--oracle-difference'.  A
signal from either buffer is returned the same way, as :error."
  (let* ((rows (plist-get case :rows))
         (cols (plist-get case :cols))
         (rejoin (plist-get case :rejoin))
         (cooked-debug t)
         (a (cooked-tests--oracle-buffer rows cols))
         (b (cooked-tests--oracle-buffer rows cols)))
    (unwind-protect
        (condition-case err
            (cl-loop
             for chunk in (plist-get case :chunks)
             for index from 0
             for bytes = (apply #'concat chunk)
             do (with-current-buffer a (cooked--feed cooked--session bytes))
             do (with-current-buffer b (cooked--feed cooked--session bytes))
             do (cooked-tests--oracle-drain a rejoin (or subject #'ignore))
             do (cooked-tests--oracle-drain b rejoin (or reference #'cooked-tests--oracle-resend))
             for difference = (cooked-tests--oracle-difference
                               (with-current-buffer a (cooked-tests--oracle-snapshot))
                               (with-current-buffer b (cooked-tests--oracle-snapshot)))
             when difference
             return (list :drain index :difference difference))
          (error (list :error err)))
      (dolist (buffer (list a b))
        (with-current-buffer buffer (cooked--cleanup))
        (kill-buffer buffer)))))

;;;; Shrinking

(defun cooked-tests--oracle-candidates (case)
  "Cases one step smaller than CASE, the biggest steps first.

A whole chunk dropped, two neighbouring chunks fed as one, then a single token
dropped."
  (let* ((chunks (plist-get case :chunks))
         (count (length chunks))
         (with (lambda (new) (plist-put (copy-sequence case) :chunks new)))
         out)
    (dotimes (i count)
      (push (funcall with (append (seq-take chunks i) (nthcdr (1+ i) chunks))) out))
    (dotimes (i (1- count))
      (push (funcall with (append (seq-take chunks i)
                                  (list (append (nth i chunks) (nth (1+ i) chunks)))
                                  (nthcdr (+ i 2) chunks)))
            out))
    (dotimes (i count)
      (let ((chunk (nth i chunks)))
        (dotimes (j (length chunk))
          (let ((smaller (append (seq-take chunk j) (nthcdr (1+ j) chunk))))
            (push (funcall with (append (seq-take chunks i)
                                        (and smaller (list smaller))
                                        (nthcdr (1+ i) chunks)))
                  out)))))
    (nreverse out)))

(defun cooked-tests--oracle-shrink (case fails)
  "The smallest case reachable from CASE for which FAILS still answers non-nil.

Greedy: the first smaller candidate that still fails is taken and shrinking
starts again from it, until no candidate fails."
  (let ((progress t))
    (while progress
      (setq progress nil)
      (when-let* ((smaller (seq-find fails (cooked-tests--oracle-candidates case))))
        (setq case smaller
              progress t)))
    case))

(defun cooked-tests--oracle-report (seed case result)
  "A failure message for the case SEED generated, shrunk to CASE, failing with RESULT."
  (let ((print-escape-control-characters t)
        (print-length nil)
        (print-level nil))
    (format "render oracle: seed %s fails; smallest script:\n  %S\nafter drain %S:\n  %S"
            seed case (plist-get result :drain)
            (or (plist-get result :difference) (plist-get result :error)))))

(defun cooked-tests--oracle-check (cases &optional subject reference)
  "Fail the current test on the first of CASES whose buffers differ.

CASES is a list of (SEED . CASE), SEED nil for a case written out by hand.
The failing case is shrunk before it is reported.  SUBJECT and REFERENCE are as for `cooked-tests--oracle-compare'."
  (pcase-dolist (`(,seed . ,case) cases)
    (when (cooked-tests--oracle-compare case subject reference)
      (let ((small (cooked-tests--oracle-shrink
                    case (lambda (c) (cooked-tests--oracle-compare c subject reference)))))
        (ert-fail (cooked-tests--oracle-report
                   seed small (cooked-tests--oracle-compare small subject reference)))))))

(defun cooked-tests--oracle-cases ()
  "The generated cases this run checks, as (SEED . CASE).

COOKED_ORACLE_CASES says how many, 200 by default, and COOKED_ORACLE_SEED
where to start, 1 by default; the Nth case is seed plus N.  So a failure
reported for seed 4711 is rerun alone with COOKED_ORACLE_SEED=4711 and
COOKED_ORACLE_CASES=1, and a wider net is a bigger count or another start."
  (let ((count (string-to-number (or (getenv "COOKED_ORACLE_CASES") "200")))
        (start (string-to-number (or (getenv "COOKED_ORACLE_SEED") "1"))))
    (mapcar (lambda (i) (cons (+ start i) (cooked-tests--oracle-generate (+ start i))))
            (number-sequence 0 (1- count)))))

;;;; Tests

(ert-deftest cooked-render-oracle-generated-cases ()
  "Every generated script leaves the buffer as resending every row would.

See the Commentary for what is compared with what.  A failure prints its seed
and the smallest script that still fails; put that script in a named test below
once the cause is understood."
  (cooked-tests--oracle-check (cooked-tests--oracle-cases)))

;; Each of these is a script the generated cases found, shrunk and then trimmed by
;; hand, kept so the bug it found stays found whatever the generator turns into.

(ert-deftest cooked-render-oracle-a-row-below-a-seam-at-the-end-of-the-buffer ()
  "A row rendered below a row 0 that continues a line at `point-max' lands on its row.

A wrapped row scrolled away and the shift deleted every screen row, leaving
`cooked--screen-start' mid-line at the very end of the buffer.  Asked for row
2 from there, `forward-line' moved nowhere and point was not at a line start,
which `cooked--goto-screen-row' took for a final line counted as moved, and
it added one newline too many: the row went a line low and the row below it
fell off the screen."
  (cooked-tests--oracle-check
   '((nil :rows 4 :cols 10 :rejoin t
          :chunks (("\e[3;6Hxy 日")
                   ("│ x │┌─" "\e[1M" "\e[2S" "│ │" "e\u0301"))))))

(ert-deftest cooked-render-oracle-clearing-a-wrapped-row-ends-its-line ()
  "Clearing the display archives its last row as a line that has ended.

`DL' under a wrapped row pulls a blank up in place of its continuation, and
the flag stays.  The clear archived the row still wrapped, so it reached the
buffer with no newline while the core said row 0 began a line."
  (cooked-tests--oracle-check
   '((nil :rows 4 :cols 7 :rejoin t :chunks (("abcdefghij" "\e[1M" "\e[H\e[2J"))))))

(ert-deftest cooked-render-oracle-clearing-under-a-scroll-region-keeps-the-seam ()
  "A clear that archives nothing leaves the head of row 0's line where it was.

Under a scroll region the clear sends nothing to history, yet the core dropped
its count of the wrapped line above the screen, which was still in the buffer."
  (cooked-tests--oracle-check
   '((nil :rows 3 :cols 7 :rejoin t
          :chunks (("──────────" "\n" "────────" "\e[2;4r" "\e[H\e[2J"))))))

(ert-deftest cooked-render-oracle-a-seam-after-combining-marks ()
  "The head of a wrapped line is counted in characters, not columns.

`e' with a combining acute is two characters on one column, so a row of them
handed to scrollback left more characters above the screen than the core
reported, and `cooked--check-seam' signalled."
  (cooked-tests--oracle-check
   '((nil :rows 4 :cols 7 :rejoin t
          :chunks (("e\u0301e\u0301" "│ x │" "┐" "\e[3;1H\e[2K 42%" "\r\n" "\r\n"))))))

(ert-deftest cooked-render-oracle-a-washed-row-the-screen-grows-back-over ()
  "A background wash below the trimmed screen arrives when the screen reaches it.

The buffer holds only the used rows, so the washed rows below were trimmed.  A
cursor moving down, or a scroll bringing one up, damages nothing, so the row
arrived as an empty line."
  (cooked-tests--oracle-check
   '((nil :rows 3 :cols 10 :rejoin t :chunks (("\e[7m" "\e[3M") ("\r\n")))
     (nil :rows 5 :cols 11 :rejoin t :chunks (("\e[1;42m" "\e[4M") ("\e[2S"))))))

(ert-deftest cooked-render-oracle-a-glyph-run-over-a-torn-wide-character ()
  "Writing over half of a wide character leaves the other half standing.

`┌─' over the first half of `語' keeps its second half as a continuation cell
with no character before it.  The core then counts the cursor after `─' one
character early, so the glyph run is cut before `─' and, once the cursor has
gone, never drawn whole again.  Known and not fixed here: every writer that
can overwrite half a wide character has to blank the other half."
  :expected-result :failed
  (cooked-tests--oracle-check
   '((nil :rows 2 :cols 6 :rejoin t :chunks (("日本語" "\r" "│ │┌─") ("\e[2;1H"))))))

(ert-deftest cooked-render-oracle-the-alternate-screen-and-a-rejoined-seam ()
  "The alternate screen agrees with the core about a rejoined seam.

It does not yet, which is why generated cases with a screen switch are never
rejoined.  Switching after a wrapped row scrolled away leaves
`cooked--screen-start' mid-line while the drain's `:head' says 0 for the
alternate screen, and a wrapped row that scrolls away in the switching drain
is given a newline while the primary's carry still counts it."
  :expected-result :failed
  (cooked-tests--oracle-check
   '((nil :rows 5 :cols 6 :rejoin t :chunks ((" 42%xy┌─" "\e[1S") ("\e[?47h")))
     (nil :rows 3 :cols 4 :rejoin t :chunks (("=======" "wwwwwww" "\e[?47h"))))))

(provide 'cooked-tests-oracle)
;;; cooked-tests-oracle.el ends here
